module.exports = {
  OPEN: "OPEN",
  CLOSE: "CLOSE",
  ONE_MESSAGE: "ONE_MESSAGE",
  NEW_MESSAGE: "NEW_MESSAGE",
  ALL_MESSAGE: "ALL_MESSAGE",
  CHANGE_MESSAGE: "CHANGE_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
};
